drop table if exists members cascade;

create table members
(
    MEMBER_ID bigint generated by default as identity,
    NAME varchar(10),
    ADDRESS varchar(100),
    PHONE varchar(100),
    PRIMARY KEY (MEMBER_ID)
)