drop table if exists members cascade;

create table members
(
    MEMBER_ID bigint generated by default as identity,
    NAME varchar(10),
    ADDRESS varchar(100),
    PHONE varchar(100),
    PRIMARY KEY (MEMBER_ID)
)
;

create table items
(
    ITEM_ID bigint generated by default as identity,
    NAME varchar(10),
    BUY_PRICE INTEGER,
    SALE_PRICE INTEGER,
    STOCK INTEGER
)
;

create table orders
(
    ORDER_ID bigint generated by default as identity,
    MEMBER_ID bigint,
    ITEM_ID  bigint,
    QUANTITY INTEGER
)